services:
  keycloak:
    image: jboss/keycloak:latest
    ports:
      - 8080:8080
    environment:
      - DB_ADDR=database
      - DB_VENDOR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak_usr
      - DB_PASSWORD=keycloak_pwd
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=123321
      - KEYCLOAK_IMPORT=/tmp/example-realm.json
    links:
      - "db:database"
    volumes:
      - "./example-realm.json:/tmp/example-realm.json"
  
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=keycloak_usr
      - POSTGRES_PASSWORD=keycloak_pwd
      - POSTGRES_DB=keycloak

